### ISSUE TITLE
ndio install fails since it can not build blosc dependancy

### ISSUE THREAD

**Issue by kkutten1** [openconnectome/ndio#225] opened 2016-07-18 23:48 UTC
| ndio version | os | python |
| --- | --- | --- |
| 1.1.3 | Centos 6.7 | 2.7.9 |

Instalation of ndio fails because blosc dependency can't be built.  I believe this error occurs because the installed gcc  (version 4.4.7) does not support "-mavx2" parameter.  I think this could be resolved by upgrading gcc (not easy since OS is in an AMI and upgrading gcc might break other software) or removing dependence on blosc.

```
$ sudo /usr/local/bin/pip install ndio
Collecting ndio
  Using cached ndio-1.1.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pillow>=3.2.0 in /usr/local/lib/python2.7/site-packages (from ndio)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.0.0 in /usr/local/lib/python2.7/site-packages (from ndio)
Requirement already satisfied (use --upgrade to upgrade): h5py>=2.6.0 in /usr/local/lib/python2.7/site-packages (from ndio)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/site-packages (from ndio)
Collecting blosc>=1.3.0 (from ndio)
  Using cached blosc-1.3.3.tar.gz
Collecting jsonschema (from ndio)
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Collecting json-spec (from ndio)
  Using cached json_spec-0.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from h5py>=2.6.0->ndio)
Collecting functools32 (from jsonschema->ndio)
  Using cached functools32-3.2.3-2.zip
Collecting pathlib (from json-spec->ndio)
  Using cached pathlib-1.0.1.tar.gz
Installing collected packages: blosc, functools32, jsonschema, pathlib, json-spec, ndio
  Running setup.py install for blosc
    Complete output from command /usr/local/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yaIiAD/blosc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vehgVe-record/install-record.txt --single-version-externally-managed --compile:
    SSE2 detected
    AVX2 detected
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/blosc
    copying blosc/test.py -> build/lib.linux-x86_64-2.7/blosc
    copying blosc/toplevel.py -> build/lib.linux-x86_64-2.7/blosc
    copying blosc/__init__.py -> build/lib.linux-x86_64-2.7/blosc
    copying blosc/version.py -> build/lib.linux-x86_64-2.7/blosc
    running build_ext
    building 'blosc.blosc_extension' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/blosc
    creating build/temp.linux-x86_64-2.7/c-blosc
    creating build/temp.linux-x86_64-2.7/c-blosc/blosc
    creating build/temp.linux-x86_64-2.7/c-blosc/internal-complibs
    creating build/temp.linux-x86_64-2.7/c-blosc/internal-complibs/lz4-1.7.2
    creating build/temp.linux-x86_64-2.7/c-blosc/internal-complibs/snappy-1.1.1
    creating build/temp.linux-x86_64-2.7/c-blosc/internal-complibs/zlib-1.2.8
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_LZ4=1 -DHAVE_SNAPPY=1 -DHAVE_ZLIB=1 -Ic-blosc/blosc -Ic-blosc/internal-complibs/snappy-1.1.1 -Ic-blosc/internal-complibs/lz4-1.7.2 -Ic-blosc/internal-complibs/zlib-1.2.8 -I/usr/local/include/python2.7 -c blosc/blosc_extension.c -o build/temp.linux-x86_64-2.7/blosc/blosc_extension.o -DSHUFFLE_SSE2_ENABLED -msse2 -DSHUFFLE_AVX2_ENABLED -mavx2
    cc1: error: unrecognized command line option "-mavx2"
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-yaIiAD/blosc/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vehgVe-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-yaIiAD/blosc
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by kkutten1** [comment] 2016-07-18 23:49
@wrgr @j6k4m8 ping

**Comment by wrgr** [comment] 2016-07-19 09:27
@gkiar - where are the instructions with the current ami build so we know what's already there/not there?

**Comment by kkutten1** [comment] 2016-07-19 10:37
@wrgr: They're on http://docs.neurodata.io/nddocs/about/ami

**Comment by Aeusman** [comment] 2016-07-19 13:47
This is the same problem with the current travis builds @wrgr

**Comment by wrgr** [comment] 2016-07-19 14:03
i'm occupied with other work today and need to resolve the nd paper edits first.  I can probably help as a background task - can you explain better what changed?  i.e., this worked last week but not today

**Comment by Aeusman** [comment] 2016-07-19 14:10
As a side note this has not been working as of 6 days ago. I'm trying a fix, but for some reason it thinks Im jordan? https://travis-ci.org/neurodata/ndio/builds/145835472

**Comment by wrgr** [comment] 2016-07-19 14:20
The latest releases of blosc (in my experience) are often ahead of the operating system default support.  Options are to either understand and fix, or just `pip install blosc==1.3.0`

Note that this broke when they pushed blosc 1.3.3 (we could post an issue there if so inclined)
https://pypi.python.org/pypi/blosc/1.3.3

@kkutten1 @j6k4m8

**Comment by Aeusman** [comment] 2016-07-19 14:33
For now Im going to try forcing an upgrade to gcc 4.9 and see if that works, if not I'll specify downgraded blosc.

**Comment by j6k4m8** [comment] 2016-07-19 14:51
Changing gcc seems like the _right_ solution, but it's possibly not worth too much engineering, since 1.3.0 → 1.3.3 doesn't change anything in blosc that we use, afaict 

Also @Aeusman — weird about the Travis listing! Are you devving on your local machine? (Feel free to slack me and we can work that out separate from this issue!)

**Comment by kkutten1** [comment] 2016-07-19 14:53
@wrgr suggestion worked!  It appears that python-blosc 1.3.3 has a bug in which it correctly detects that the CPU supports AVX2 but fails to detect if gcc supports it.  Maybe ndio's setup.py should only request  blosc==1.3.0.  So @Aeusman there's no need to upgrade compiler at this time.

**Comment by Aeusman** [comment] 2016-07-19 14:58
@j6k4m8 reproducible when I create a new branch on a local machine and set upstream without pushing a commit. Interesting because I'm using SSL keys so there really shouldn't be an issue. When I push a commit  it says I wrote it so authentication failure doesn't persist, possible github bug. 

For fixing this in travis updating the compiler is better from a design standpoint, better to get latest dependencies in case of bug fixes.

**Comment by Aeusman** [comment] 2016-07-19 15:19
https://github.com/neurodata/ndio/pull/226

Fixed - @wrgr and @j6k4m8 I recommend pulling in soon so other prs can be approved.

**Comment by kkutten1** [comment] 2016-07-19 15:27
@j6k4m8 please see pull request https://github.com/neurodata/ndio/pull/227

**Comment by wrgr** [comment] 2016-07-19 15:33
fixed via @Aeusman 's PR

**Closed as completed by wrgr** 2016-07-19 15:33 UTC
