### ISSUE TITLE
SpiralScience Assistance Needed

### ISSUE THREAD

**Issue by mlee156** [openconnectome/ndio#73] opened 2016-02-15 13:33 UTC
My group is having issues getting data directly using the metadata info - I'm pretty sure this is not a bug and we are doing something wrong, but unfortunately we weren't able to find the answer.

``` python
#!/usr/bin/python
#-*- coding:utf-8 -*-
from __builtin__ import *

import ndio
import ndio.remote.neurodata as ND
import numpy as np
import pprint

TOKEN = 'fear199'
CHANNEL = 'grayscale'
DATAPATH = '../data/'

nd = ND()

def getMetaData(token):
    metadata = nd.get_proj_info(token)
    return metadata

def main():
    print 'ndio version =',ndio.version

    metaData = getMetaData(TOKEN)
    #pprint.pprint(metaData,indent=4)
    imagesSizes = metaData['dataset']['imagesize']
    offset = metaData['dataset']['offset']

    n = u'5' # resolution
    print "ndio get cutout ... TOKEN=%s CHANNEL=%s RESOLUTION=%s"%(TOKEN,CHANNEL,n)
    data = nd.get_cutout(TOKEN,CHANNEL,
                        offset[n][0],imagesSizes[n][0],
                        offset[n][1],imagesSizes[n][1],
                        offset[n][2],imagesSizes[n][2],
                        resolution=int(n))
    outFile = DATAPATH+'%s_%s_%s.csv'%(TOKEN,CHANNEL,n)
    np.savetxt(outFile,
                data,
                delimiter=',')
    print "... Finished ... OUTPUT=%s"%(outFile)

if __name__ == '__main__':
    main()
```

This is the direct link to the getData.py file: https://github.com/Upward-Spiral-Science/claritycontrol/tree/master/code/scripts

**Comment by j6k4m8** [comment] 2016-02-15 16:06
I edited your question to have syntax-highlighting. Can you explain the problem you're running into? I'm on my phone's hotspot and can't download large data volumes like this to check that things are working.

**Comment by wrgr** [comment] 2016-02-15 16:39
@alee156:  What are you trying to with this script?  I wanted to pop up a level - are you trying to get image data?  anno data?  Metadata?  If metadata, what kind?

And as @j6k4m8 comments, what error are you getting?

**Comment by jovo** [comment] 2016-02-15 16:47
@kkutten1 can you send @alee156 a downsampled clarity brain?  something small enough to fit into ram.  any brain is fine, obtained any method is fine.  put it on dropbox if we have to.  we can fix the download script later. thanks all.

**Comment by wrgr** [comment] 2016-02-15 17:02
Do this @alee156:

First query a token to get it's bounds: 
http://openconnecto.me/ocp/ca/Fear199/info

We observe an offset of [0,0,0] and a size of [540, 717, 1358] at scale 5 (the lowest scale available).  Multiplying these dimensions shows that the entire dataset is about 500MB.

You can get this directly (no api required) in hdf5 format with the following command:
http://openconnecto.me/ocp/ca/Fear199/hdf5/5/0,540/0,717/0,1358/

hdfview is a free program provided by the hdf group (who set the hdf5 standard) that show you what fields are present and how the data are organized.

**Comment by jovo** [comment] 2016-02-15 17:51
@willgray at some point we should write a generic tutorial for how to download a arbitrary cube of data.
not a high priority, but prior to paper being published

**Comment by wrgr** [comment] 2016-02-15 18:45
@jovo:  Do you want something more than this?  

http://docs.neurodata.io/nddocs/tutorials.html

Perhaps I could also include the discussion above and a link to the restful docs.  but this is nearing completion imho.

**Comment by jovo** [comment] 2016-02-15 18:49
i don't know.

@alee156 can you download the data successfully by reading that page?

**Comment by mlee156** [comment] 2016-02-15 19:21
I used the tutorials very extensively but I don't have enough coding experience as I should have, and while I think that a little more information would have been helpful, someone with more coding experience would probably be able to get the data easily. 

The http://openconnecto.me/ocp/ca/Fear199/hdf5/5/0,540/0,717/0,1358/ link isn't loading for me unfortunately :/ . 

We were able to parse the metadata information without any problem we just always get a timeout error.

Thank you so much for the help!

**Comment by wrgr** [comment] 2016-02-15 19:26
easiest to access link in a browser - i use chrome.  I've downloaded it twice.  It's relatively large and the connection will time out (takes a couple minutes on my 75MB connection to send request, wait for packaging and download), so if your home internet is slow (?) that could be the culprit.  Tell us more?

**Comment by mlee156** [comment] 2016-02-15 19:48
That makes sense - the hopkins internet has been really sketchy lately - i'll try buying an ethernet.

**Comment by jovo** [comment] 2016-02-15 19:56
@alee156 you can pick one up from anthony.

**Comment by wrgr** [comment] 2016-02-15 20:03
to try things out, you could run this:  http://openconnecto.me/ocp/ca/Fear199/hdf5/5/0,540/0,717/1000,1050/ 

to get a few slices and verify that this is the issue  good luck!  (~15MB)

**Comment by kkutten1** [comment] 2016-02-15 21:21
@alee156 I've shared the Control239 and Fear199 at a 25 um resolution with you.  Do you have a CIS account?  If so I can give you higher resolution versions.

**Comment by kkutten1** [comment] 2016-02-15 21:25
@alee156 Also the API is case sensitive so you need to capitalize the F
`
 TOKEN = 'Fear199'
`

**Comment by mlee156** [comment] 2016-02-15 21:38
Hmmm.... Even the smaller slices aren't downloading immediately

I'll try going to Brody and try it, maybe it's just my router?

**Comment by mlee156** [comment] 2016-02-15 21:39
How do you apply for a CIS account?

**Comment by jovo** [comment] 2016-02-15 21:41
i just emailed anthony.

On Mon, Feb 15, 2016 at 4:39 PM, alee156 notifications@github.com wrote:

> How do you apply for a CIS account?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndio/issues/73#issuecomment-184405276.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by j6k4m8** [comment] 2016-02-16 02:54
If you're still having trouble, I wrote `ndio.remote#ping()` for just this sort of troubleshooting. 

``` python
import ndio.remote.neurodata as ND
nd = ND()

nd.ping()
```

Try this. You should get a `200` response (success). If not, then the problem is network connectivity — you can't see the API endpoints. If you get a 200, then it's very possible that the issue is network speed, or perhaps something more nuanced, like a bad request.

**Comment by j6k4m8** [comment] 2016-02-18 18:53
@alee156 any update on this? Let me know if we can close this.

**Comment by wrgr** [comment] 2016-02-20 12:34
administratively closing.  if problems still exist, please reopen.

**Closed as completed by wrgr** 2016-02-20 12:34 UTC
Labels: bug, question, low priority, needs-repro

**Comment by mlee156** [comment] 2016-02-20 19:08
Hi sorry, Jordan helped fix the problem in class - everything should be fine now! Thanks!
